describe('Unit Tracker as a basic user', () => {
  
//login - test is working
  // it('should enter login credentials and click the alert roster',  () => {
  //   cy.visit('http://localhost:3000')
  //   cy.findAllByRole('textbox', {name: 'DOD ID'})
  //   .type('1234567899')
  //   cy.tab()
  //   .type('111223333')
  //   cy.findByRole('button', {name: 'Alert Roster'})
  //   .click()
  //   cy.findByRole('button', {name: 'Logout'})
  //   .click()
  //   cy.pause()
  // })
//update info

  //Register a new Soldier
  // it('should navigate to registration page and fill in data',  () => {
  //   cy.visit('http://localhost:3000')
  //   cy.findByRole('button', {name: 'Registration'})
  //   .click()
  //   cy.findAllByRole('textbox').eq(0)
  //   .type('Chandler')
  //   cy.tab()
  //   .type('Robert')
  //   cy.tab()
  //   .type('R')
  //   cy.tab()
  //   .type('111223333')
  //   cy.tab()
  //   .type('1234567899')
  //   cy.tab()
  //   cy.tab()
  //   cy.tab()
  //   .type('ACB123')
  //   cy.tab()
  //   .type('1')
  //   cy.tab()
  //   .type('11B')
  //   cy.tab()
  //   .type('1984-09-17')
  //   cy.tab()
  //   .type('38')
  //   cy.tab()
  //   .type('170')
  //   cy.tab()
  //   .type('69')
  //   cy.tab()
  //   .type('AB POS')
  //   cy.tab()
  //   .type('1234567890')
  //   cy.tab()
  //   .type('123 Main St')
  //   cy.tab()
  //   .type('{enter}')

})

describe('Unit tracker as an admin', () => {
  it('should enter login credentials and click the login button',  () => {
    cy.visit('http://localhost:3000')
    cy.findAllByRole('textbox', {name: 'DOD ID'})
    .type('1928477713')
    cy.tab()
    .type('200992888')
    cy.findByRole('button', {name: "Leaders' Portal"})
    .click()
    cy.pause()
    cy.findByRole('link', {name: "Chandler"})
    .click()
  })
})

  // it('should navigate to splashpage', () => {
  //   cy.findByRole('heading').should('contain', 'Unit Tracker')
  //   cy.findAllByRole('textbox', {name: 'DOD ID'})
  //   .click()
  //   .type('1383391993')
  //   cy.findAllByRole('textbox', {name: 'Social Security Number'})
  //   .click()
  //   .type('111223333')
// })
